SOURCES =	llist_add_back.c llist_add_front.c \
			llist_clear.c llist_delone.c llist_insert.c \
			llist_iter.c llist_last.c llist_map.c \
			llist_new.c llist_size.c \
			tests\test_llist_size.c \
			../munit/munit.c

all: ${OBJECTS}
	gcc -Wall -Werror -Wextra ${SOURCES}
